version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: manzoor
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: wp_mydb
    volumes:
      - db_storage:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    ports:
      - 8080:80
    image: wordpress:5.1.1-php7.3-apache
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=manzoor
      - WORDPRESS_DB_PASSWORD=redhat
      - WORDPRESS_DB_NAME=wp_mydb
    volumes:
      - wp_storage:/var/www/html
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - app-network
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8081:8080
    networks:
      - app-network

volumes:
  db_storage:
  wp_storage:

networks:
  app-network:
    driver: bridge
